image: node:12-buster

# See https://angular.io/guide/testing#configure-project-for-gitlab-ci
variables:
  FF_USE_FASTZIP: "true"

cache:
  untracked: true
  policy: push
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - frontend/monastic-matrix/node_modules/

.pull_cached_node_modules:
  cache:
    untracked: true
    key: ${CI_COMMIT_SHORT_SHA}
    policy: pull

stages:
  - build
  - deploy-dev
#  - deploy-prod

build:
  stage: build
  extends: .pull_cached_node_modules
  before_script:
    - npm install -g @angular/cli
    - cp src/environments/environment.ts.template src/environments/environment.ts
    - cp src/environments/environment.prod.ts.template src/environments/environment.prod.ts
  script:
    - npm install
    - ng build --configuration=production --base-href /$URL_PATH/ --baseHref /$URL_PATH/
  after_script:
    - tar czf pure-external-orgs.tar.gz ./dist/*
  artifacts:
    paths:
      - pure-external-orgs.tar.gz

.ssh_setup:
  before_script:
    - apt-get update -qq
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)

.ssh_finish_config:
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

deploy-dev:
  stage: deploy-dev
  extends: .pull_cached_node_modules
  before_script:
    - !reference [build, before_script]
    - !reference [.ssh_setup, before_script]
    - echo "$DEV_SSH_KEY" | tr -d '\r' | ssh-add -
    - !reference [.ssh_finish_config, before_script]
  script:
    - !reference [build, script]
    - sed -i "s/PURE_TEST_URL/$DEV_PURE_TEST_URL/" src/environments/environment*ts
    - sed -i "s/PURE_TEST_PROXY_URL/$DEV_PURE_TEST_PROXY_URL/" src/environments/environment*ts
    - sed -i "s/PURE_LIVE_URL/$DEV_PURE_LIVE_URL/" src/environments/environment*ts
    - sed -i "s/PURE_LIVE_PROXY_URL/$DEV_PURE_LIVE_PROXY_URL/" src/environments/environment*ts
    - ssh -o stricthostkeychecking=no $DEV_USER@$DEV_SERVER "rm -fr $DEV_SERVER_PATH/*"
    - scp -o stricthostkeychecking=no -r ./dist/pure-external-orgs/* $DEV_USER@$DEV_SERVER:~/pure-external-orgs
  only:
    - main

# deploy-prod:
#   stage: deploy-prod
#   extends: .pull_cached_node_modules
#   before_script:
#     - !reference [build, before_script]
#     - !reference [.ssh_setup, before_script]
#     - echo "$PROD_SSH_KEY" | tr -d '\r' | ssh-add -
#     - !reference [.ssh_finish_config, before_script]
#   script:
#     - !reference [build, script]
#     - ssh -o stricthostkeychecking=no $PROD_USER@$PROD_SERVER "rm -r $PROD_SERVER_PATH/*"
#     - scp -o stricthostkeychecking=no -r ./dist/pure-external-orgs/* $PROD_USER@$PROD_SERVER:$PROD_SERVER_PATH
#   only:
#     - tags
