image: node:12-buster

# See https://angular.io/guide/testing#configure-project-for-gitlab-ci
variables:
  FF_USE_FASTZIP: "true"

cache:
  untracked: true
  policy: push
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - frontend/monastic-matrix/node_modules/

.pull_cached_node_modules:
  cache:
    untracked: true
    key: ${CI_COMMIT_SHORT_SHA}
    policy: pull

stages:
  - build

build:
  stage: build
  extends: .pull_cached_node_modules
  before_script:
    - npm install -g @angular/cli
  script:
    - npm install
    - ng build --prod --configuration=production
    - tar czf pure-external-orgs.tar.gz ./dist/*
  artifacts:
    paths:
      - pure-external-orgs.tar.gz
